import { useContext } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import MenuBar from "../Components/MenuBar";
import Home from "../Components/Home";
import Link from "next/link";
import classnames from "classnames";
import Image from "next/image";
import { Grid } from "@mui/material";
import ConnectWallet from "./ConnectWallet";

const Template = ({ showLeft, title, children, extraLink, extraHead }) => {
  return (
    <div className={classnames(styles.container, styles.patternBackground)}>
      <Head>
        <title>AlphaTwt : {title}</title>
        <meta name="description" content="Generated by AlphaTwt" />
        <link rel="icon" href="/favicon.ico" />
        {extraHead}
      </Head>

      <main className={styles.main}>
        {showLeft && (
          <header>
            <div>
              <Image
                src="/assets/alphatwtLogo.png"
                alt="alphatwtLogo"
                width="961"
                height="128"
                layout="intrinsic"
              />
            </div>
          </header>
        )}
        <Grid container alignItems="center" style={{ margin: "2rem" }}>
          <Grid item xs={12} lg={10}>
            <Grid container spacing={3}>
              <Grid item xs={12} md={4}>
                <h2>Create your tweet & monetize it right at start.</h2>
                <p>
                  AlphaTweet enables you to token-gate your tweets & empower
                  your followers to earn rewards.
                </p>
              </Grid>
              {children}
            </Grid>
          </Grid>
        </Grid>
        <MenuBar extraLink={extraLink} />
      </main>
    </div>
  );
};

export default Template;
