import { useContext } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import MenuBar from "../Components/MenuBar";
import Home from "../Components/Home";
import Link from "next/link";
import classnames from "classnames";
import Image from "next/image";

const Template = ({ showLeft, title, children, extraLink, extraHead }) => {
  return (
    <div className={classnames(styles.container, styles.patternBackground)}>
      <Head>
        <title>AlphaTwt : {title}</title>
        <meta name="description" content="Generated by AlphaTwt" />
        <link rel="icon" href="/favicon.ico" />
        {extraHead}
      </Head>

      <main className={styles.main}>
        {showLeft && (
          <header>
            <div>
              <Image
                src="/assets/alphatwtLogo.png"
                alt="alphatwtLogo"
                width="961"
                height="128"
                layout="intrinsic"
              />
            </div>
          </header>
        )}
        <MenuBar extraLink={extraLink} />
        {children}
      </main>
    </div>
  );
};

export default Template;
