import Head from "next/head";

import AsciiHeader from "./AsciiHeader";

const Template = ({ title, children, extraHead }) => {
  return (
    <div className="container max-w-[992px] mx-auto px-4 pt-8 text-gray">
      <Head>
        <title>AlphaTwt : {title}</title>
        <meta name="description" content="Generated by AlphaTwt" />
        <link rel="icon" href="/favicon.ico" />
        {extraHead}
      </Head>
      <AsciiHeader />
      <main className="mt-8 md:mt-20 mb-40">{children}</main>
      <footer className="text-center text-sm mb-4">
        Alpha. Built by (and with!){" "}
        <a className="font-semibold" href="https://unlock-protocol.com/">
          Unlock Protocol
        </a>
      </footer>
    </div>
  );
};

export default Template;
